version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop-performance
    versions:
    - 1.10.0
  - dependency-name: rubocop
    versions:
    - 1.9.0
