require: rubocop-performance
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
    - 'example/**/*'
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/LineLength:
  Max: 120
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/UriEscapeUnescape:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 18
  Exclude:
    - app/controllers/core/cli_options.rb
Metrics/PerceivedComplexity:
  Max: 9
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/FormatStringToken:
  Exclude:
    - lib/cms_scanner/finders/finder.rb
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/MixinUsage:
  Exclude:
    - lib/cms_scanner/formatter.rb
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
